AutoRest code generation utility [cli version: 3.1.5; node: v14.16.1, max-memory: 2048 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      '/home/vsts/.autorest/@autorest_core@3.0.6219/node_modules/@autorest/core/dist' (3.0.6219)
   Installing AutoRest extension '@autorest/terraform' (https://terraformcodegen.blob.core.windows.net/terraformcodegen/autorest-terraform-latest.tgz)
   Installed AutoRest extension '@autorest/terraform' (https://terraformcodegen.blob.core.windows.net/terraformcodegen/autorest-terraform-latest.tgz->2.0.0)
   Installing AutoRest extension '@autorest/modelerfour' (4.17.1)
   Installed AutoRest extension '@autorest/modelerfour' (4.17.1->4.17.1)

WARNING (PreCheck/SchemaMissingType): The schema 'ComplianceResultList' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'PricingList' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'AdvancedThreatProtectionProperties' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'TagsResource' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'IoTSecuritySolutionsList' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'IoTSecuritySolutionAnalyticsModelProperties' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'IoTSecuritySolutionAnalyticsModelProperties-devicesMetricsItem' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'IoTSecuritySolutionAnalyticsModelList' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'IoTSecurityAggregatedAlertList' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'IoTSecurityAggregatedRecommendationList' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'IoTSecurityAggregatedAlertProperties-topDevicesListItem' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'TagsResource' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'WorkspaceSettingList' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'RegulatoryComplianceStandardList' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'RegulatoryComplianceControlList' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'RegulatoryComplianceAssessmentList' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'AutomationList' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'Rule' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'EffectiveNetworkSecurityGroups' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'AdaptiveNetworkHardeningProperties' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'AdaptiveNetworkHardening' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'AdaptiveNetworkHardeningsList' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'ExternalSecuritySolutionList' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'DeviceList' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'ErrorAdditionalInfo' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/CheckDuplicateSchemas): Checking for duplicate schemas, this could take a (long) while.  Run with --verbose for more detail.

WARNING (PreCheck/DuplicateSchema): Duplicate Schema named ExternalSecuritySolutionKind -- type: undefined => "string",properties: {"kind":{"description":"The kind of the external solution","$ref":"#/components/schemas/ExternalSecuritySolutionKind"}} => <none>,enum: undefined => ["CEF","ATA","AAD"],x-ms-enum: undefined => {"name":"ExternalSecuritySolutionKind","modelAsString":true,"values":[{"value":"CEF"},{"value":"ATA"},{"value":"AAD"}]} 

WARNING (PreCheck/DuplicateSchema): Duplicate Schema named AadConnectivityState -- type: undefined => "string",properties: {"connectivityState":{"$ref":"#/components/schemas/AadConnectivityState"}} => <none>,title: undefined => "The connectivity state of the external AAD solution ",enum: undefined => ["Discovered","NotLicensed","Connected"],x-ms-enum: undefined => {"name":"AadConnectivityState","modelAsString":true,"values":[{"value":"Discovered"},{"value":"NotLicensed"},{"value":"Connected"}]} 
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-584-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fstable-2F2019-08-01-2Fexamples-2FIoTSecuritySolutionsAnalytics-2FGetIoTSecuritySolutionsSecurityAnalyticsList.json'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 299)
(node:2187) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-586-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fstable-2F2019-08-01-2Fexamples-2FIoTSecuritySolutionsAnalytics-2FGetIoTSecuritySolutionsSecurityAggregatedAlertList.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 300)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-587-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fstable-2F2019-08-01-2Fexamples-2FIoTSecuritySolutionsAnalytics-2FGetIoTSecuritySolutionsSecurityAggregatedAlert.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 301)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-588-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fstable-2F2019-08-01-2Fexamples-2FIoTSecuritySolutionsAnalytics-2FPostIoTSecuritySolutionsSecurityAggregatedAlertDismiss.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 302)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-589-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fstable-2F2019-08-01-2Fexamples-2FIoTSecuritySolutionsAnalytics-2FGetIoTSecuritySolutionsSecurityRecommendation.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 303)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-590-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fstable-2F2019-08-01-2Fexamples-2FIoTSecuritySolutionsAnalytics-2FGetIoTSecuritySolutionsSecurityRecommendationList.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 304)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-616-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fpreview-2F2017-08-01-preview-2Fexamples-2FAutoProvisioningSettings-2FGetAutoProvisioningSettingsSubscription_example.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 305)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-617-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fpreview-2F2017-08-01-preview-2Fexamples-2FAutoProvisioningSettings-2FGetAutoProvisioningSettingSubscription_example.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 306)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-618-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fpreview-2F2017-08-01-preview-2Fexamples-2FAutoProvisioningSettings-2FCreateAutoProvisioningSettingsSubscription_example.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 307)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-623-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fpreview-2F2017-08-01-preview-2Fexamples-2FInformationProtectionPolicies-2FGetCustomInformationProtectionPolicy_example.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 308)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-624-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fpreview-2F2017-08-01-preview-2Fexamples-2FInformationProtectionPolicies-2FGetEffectiveInformationProtectionPolicy_example.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 309)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-625-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fpreview-2F2017-08-01-preview-2Fexamples-2FInformationProtectionPolicies-2FCreateOrUpdateInformationProtectionPolicy_example.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 310)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-626-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fpreview-2F2017-08-01-preview-2Fexamples-2FInformationProtectionPolicies-2FListInformationProtectionPolicies_example.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 311)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-644-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fpreview-2F2019-01-01-preview-2Fexamples-2FRegulatoryCompliance-2FgetRegulatoryComplianceStandardList_example.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 312)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-648-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fpreview-2F2019-01-01-preview-2Fexamples-2FRegulatoryCompliance-2FgetRegulatoryComplianceAssessmentList_example.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 313)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-665-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fpreview-2F2019-01-01-preview-2Fexamples-2FAlertsSuppressionRules-2FGetAlertsSuppressionRulesWithAlertType_example.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 314)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-670-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fstable-2F2020-01-01-2Fexamples-2FServerVulnerabilityAssessments-2FListByExtendedResourceServerVulnerabilityAssessments_example.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 315)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-672-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fstable-2F2020-01-01-2Fexamples-2FServerVulnerabilityAssessments-2FCreateServerVulnerabilityAssessments_example.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 316)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-673-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fstable-2F2020-01-01-2Fexamples-2FServerVulnerabilityAssessments-2FDeleteServerVulnerabilityAssessments_example.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 317)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-688-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fstable-2F2020-01-01-2Fexamples-2FApplicationWhitelistings-2FGetAdaptiveApplicationControlsSubscription_example.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 318)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-693-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fstable-2F2020-01-01-2Fexamples-2FAdaptiveNetworkHardenings-2FListByExtendedResourceAdaptiveNetworkHardenings_example.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 319)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-706-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fstable-2F2020-01-01-2Fexamples-2FJitNetworkAccessPolicies-2FGetJitNetworkAccessPoliciesSubscriptionLocation_example.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 320)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-707-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fstable-2F2020-01-01-2Fexamples-2FJitNetworkAccessPolicies-2FGetJitNetworkAccessPoliciesResourceGroup_example.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 321)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-708-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fstable-2F2020-01-01-2Fexamples-2FJitNetworkAccessPolicies-2FGetJitNetworkAccessPoliciesResourceGroupLocation_example.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 322)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-714-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fstable-2F2020-01-01-2Fexamples-2FDiscoveredSecuritySolutions-2FGetDiscoveredSecuritySolutionsSubscription_example.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 323)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-715-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fstable-2F2020-01-01-2Fexamples-2FDiscoveredSecuritySolutions-2FGetDiscoveredSecuritySolutionsSubscriptionLocation_example.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 324)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-716-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fstable-2F2020-01-01-2Fexamples-2FDiscoveredSecuritySolutions-2FGetDiscoveredSecuritySolutionResourceGroupLocation_example.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 325)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-718-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fstable-2F2020-01-01-2Fexamples-2FSecuritySolutionsReferenceData-2FGetSecuritySolutionsReferenceDataSubscription_example.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 326)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-719-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fstable-2F2020-01-01-2Fexamples-2FSecuritySolutionsReferenceData-2FGetSecuritySolutionsReferenceDataSubscriptionLocation_example.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 327)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-721-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fstable-2F2020-01-01-2Fexamples-2FExternalSecuritySolutions-2FGetExternalSecuritySolutionsSubscription_example.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 328)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-722-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fstable-2F2020-01-01-2Fexamples-2FExternalSecuritySolutions-2FGetExternalSecuritySolutionsSubscriptionLocation_example.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 329)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-731-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fstable-2F2020-01-01-2Fexamples-2FsecureScoreControlDefinitions-2FListSecureScoreControlDefinitions_subscription_example.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 330)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-739-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fpreview-2F2020-01-01-preview-2Fexamples-2FConnectors-2FCreateUpdateAwsAssumeRoleConnectorSubscription_example.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 331)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-740-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fpreview-2F2020-01-01-preview-2Fexamples-2FConnectors-2FCreateUpdateGcpCredentialsConnectorSubscription_example.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 332)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-744-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fpreview-2F2020-07-01-preview-2Fexamples-2FsqlVulnerabilityAssessmentScanOperations-2FArcMachineScans_GetLatest.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 333)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-747-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fpreview-2F2020-07-01-preview-2Fexamples-2FsqlVulnerabilityAssessmentsScanResultsOperations-2FArcMachineScanResults_Get.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 334)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-748-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fpreview-2F2020-07-01-preview-2Fexamples-2FsqlVulnerabilityAssessmentsScanResultsOperations-2FArcMachineScanResults_GetLatest.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 335)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-749-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fpreview-2F2020-07-01-preview-2Fexamples-2FsqlVulnerabilityAssessmentsScanResultsOperations-2FArcMachineScanResults_List.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 336)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-750-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fpreview-2F2020-07-01-preview-2Fexamples-2FsqlVulnerabilityAssessmentsScanResultsOperations-2FArcMachineScanResults_ListLatest.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 337)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-752-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fpreview-2F2020-07-01-preview-2Fexamples-2FsqlVulnerabilityAssessmentsBaselineRuleOperations-2FArcMachineBaselineRules_Put.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 338)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-753-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fpreview-2F2020-07-01-preview-2Fexamples-2FsqlVulnerabilityAssessmentsBaselineRuleOperations-2FArcMachineBaselineRules_PutLatest.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 339)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-754-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fpreview-2F2020-07-01-preview-2Fexamples-2FsqlVulnerabilityAssessmentsBaselineRuleOperations-2FArcMachineBaselineRules_Get.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 340)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-755-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fpreview-2F2020-07-01-preview-2Fexamples-2FsqlVulnerabilityAssessmentsBaselineRuleOperations-2FArcMachineBaselineRules_Delete.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 341)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-756-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fpreview-2F2020-07-01-preview-2Fexamples-2FsqlVulnerabilityAssessmentsBaselineRuleOperations-2FArcMachineBaselineRules_List.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 342)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-757-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fpreview-2F2020-07-01-preview-2Fexamples-2FsqlVulnerabilityAssessmentsBaselineRuleOperations-2FArcMachineBaselineRules_Add.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 343)
(node:2187) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open '/tmp/autorest-z13NPA/mem-758-file-3A-2F-2F-2Fhome-2Fvsts-2Fwork-2F1-2Fs-2Fazure-rest-api-specs-2Fspecification-2Fsecurity-2Fresource-manager-2FMicrosoft.Security-2Fpreview-2F2020-07-01-preview-2Fexamples-2FsqlVulnerabilityAssessmentsBaselineRuleOperations-2FArcMachineBaselineRules_AddLatest.json'
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 344)
WARNING: Please add the predefined profile: microsoft.devices/iothubs.
WARNING: Please add the predefined profile: microsoft.operationalinsights/workspaces.
WARNING: Please add the predefined profile: microsoft.operationalinsights/workspaces.
WARNING: Please add the predefined profile: microsoft.logic/workflows.
WARNING: Please add the predefined profile: microsoft.security/locations.
WARNING: Please add the predefined profile: microsoft.security/locations.
WARNING: Please add the predefined profile: microsoft.security/sqlvulnerabilityassessments.
WARNING: Please add the predefined profile: microsoft.security/sqlvulnerabilityassessments/baselinerules.
WARNING: Please add the predefined profile: microsoft.security/iotdefendersettings.
WARNING: Please add the predefined profile: microsoft.operationalinsights/workspaces.
WARNING: Please add the predefined profile: microsoft.security/iotsites.
[82.69 s] Generation Complete
